server:
  port: 80
spring:
  application:
    name: consul-order-service

  cloud:
    consul:
      #注册中心地址
      host: 162.14.77.50
      #端口
      port: 8500
      discovery:
        #        hostname: 162.14.77.50
        service-name: ${spring.application.name}
        # 开启的心跳机制没有打开，健康检查总是报红
        heartbeat:
          enabled: true